version: '3.8'

services:
  animefrito-frontend:
    build: .
    container_name: animefrito_frontend
    ports:
      - "8080:80"
    restart: always
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1 # Update this in production
    networks:
      - animefrito-network

networks:
  animefrito-network:
    driver: bridge
